/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bridge_NativeFilterBridge */

#ifndef _Included_bridge_NativeFilterBridge
#define _Included_bridge_NativeFilterBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bridge_NativeFilterBridge
 * Method:    processImage
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_bridge_NativeFilterBridge_processImage
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
